### ISSUE TITLE
What API are you using?

### ISSUE THREAD

**Issue by s-stefanov** [josepo/qatar2022#1]
Hello,

I would like to create similiar personal application for betting with friends on the World Cup.
I saw you are using Firebase as a backend. Do you use call open API for retrieving the match data for the groups/day matches etc.?

Thank you in advance.

**Comment by josepo** [comment]
Hi there! That was my original idea but due to time restrictions I think I'll hardcode the whole thing. Do let me know if you find an API, that would be nice to know.

**Comment by s-stefanov** [comment]
I decided to go with https://www.api-football.com/documentation-v3#tag/Fixtures

They have a free 100 requests per day and this will be enough for me to update the scores/matches per some minutes. 
Will store the whole data inside a Mongo and will query what I need.

**Comment by josepo** [comment]
Thanks for letting me know man! I appreciate it!
